"""initial_schema

Revision ID: b08efca584e3
Revises:
"""

from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = "b08efca584e3"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("actor_id", sa.BigInteger(), nullable=False),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("entity_id", sa.Integer(), nullable=False),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "contests",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=180), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("summary", sa.String(length=1000), nullable=False),
        sa.Column("full_task", sa.Text(), nullable=False),
        sa.Column("rules", sa.Text(), nullable=False),
        sa.Column("max_participants", sa.Integer(), nullable=False),
        sa.Column("fee_tjs", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("prize_first_tjs", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("prize_second_tjs", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("prize_third_tjs", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("registration_deadline", sa.DateTime(timezone=True), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("freeze_reason", sa.Text(), nullable=True),
        sa.Column("cancel_reason", sa.Text(), nullable=True),
        sa.Column("frozen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("previous_status", sa.String(length=20), nullable=True),
        sa.Column("actual_started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("published", sa.Boolean(), nullable=False),
        sa.Column("results_published", sa.Boolean(), nullable=False),
        sa.Column("results_published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("next_participant_no", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('draft','scheduled','running','frozen','finished','cancelled')", name="contest_status"
        ),
        sa.CheckConstraint(
            "fee_tjs >= 0 AND prize_first_tjs >= 0 AND prize_second_tjs >= 0 AND prize_third_tjs >= 0",
            name="nonnegative_money",
        ),
        sa.CheckConstraint("max_participants > 0", name="positive_capacity"),
        sa.CheckConstraint("registration_deadline < starts_at AND starts_at < ends_at", name="contest_dates"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_index(op.f("ix_contests_ends_at"), "contests", ["ends_at"], unique=False)
    op.create_index(op.f("ix_contests_starts_at"), "contests", ["starts_at"], unique=False)
    op.create_index(op.f("ix_contests_status"), "contests", ["status"], unique=False)
    op.create_table(
        "notifications",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("event_key", sa.String(length=200), nullable=False),
        sa.Column("chat_id", sa.BigInteger(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("lease_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.String(length=100), nullable=True),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("event_key"),
    )
    op.create_index(op.f("ix_notifications_available_at"), "notifications", ["available_at"], unique=False)
    op.create_index(op.f("ix_notifications_status"), "notifications", ["status"], unique=False)
    op.create_table(
        "oauth_attempts",
        sa.Column("state_hash", sa.String(length=64), nullable=False),
        sa.Column("browser_hash", sa.String(length=64), nullable=False),
        sa.Column("verifier", sa.String(length=128), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("state_hash"),
    )
    op.create_index(op.f("ix_oauth_attempts_expires_at"), "oauth_attempts", ["expires_at"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("telegram_id", sa.BigInteger(), nullable=False),
        sa.Column("oidc_subject", sa.String(length=255), nullable=True),
        sa.Column("username", sa.String(length=64), nullable=True),
        sa.Column("first_name", sa.String(length=255), nullable=False),
        sa.Column("last_name", sa.String(length=255), nullable=True),
        sa.Column("photo_url", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("oidc_subject"),
        sa.UniqueConstraint("telegram_id"),
    )
    op.create_table(
        "login_sessions",
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("token_hash"),
    )
    op.create_index(op.f("ix_login_sessions_expires_at"), "login_sessions", ["expires_at"], unique=False)
    op.create_index(op.f("ix_login_sessions_user_id"), "login_sessions", ["user_id"], unique=False)
    op.create_table(
        "participations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("contest_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("participant_no", sa.Integer(), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('awaiting_payment','payment_pending','approved','rejected')", name="participation_status"
        ),
        sa.ForeignKeyConstraint(
            ["contest_id"],
            ["contests.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("contest_id", "participant_no", name="uq_participant_number"),
        sa.UniqueConstraint("contest_id", "user_id", name="uq_participation"),
    )
    op.create_index(op.f("ix_participations_contest_id"), "participations", ["contest_id"], unique=False)
    op.create_index(op.f("ix_participations_user_id"), "participations", ["user_id"], unique=False)
    op.create_table(
        "payments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("participation_id", sa.Integer(), nullable=False),
        sa.Column("amount_tjs", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("receipt_path", sa.String(length=200), nullable=False),
        sa.Column("original_name", sa.String(length=255), nullable=False),
        sa.Column("mime_type", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("reject_reason", sa.Text(), nullable=True),
        sa.Column("reviewed_by", sa.BigInteger(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("status IN ('pending','approved','rejected')", name="payment_status"),
        sa.ForeignKeyConstraint(
            ["participation_id"],
            ["participations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("participation_id"),
    )
    op.create_index(op.f("ix_payments_status"), "payments", ["status"], unique=False)
    op.create_table(
        "submissions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("participation_id", sa.Integer(), nullable=False),
        sa.Column("bot_username", sa.String(length=32), nullable=False),
        sa.Column("bot_url", sa.String(length=100), nullable=False),
        sa.Column("github_url", sa.String(length=300), nullable=True),
        sa.Column("source_file_path", sa.String(length=200), nullable=False),
        sa.Column("source_original_name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["participation_id"],
            ["participations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("participation_id"),
    )
    op.create_table(
        "scores",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("submission_id", sa.Integer(), nullable=False),
        sa.Column("judge_telegram_id", sa.BigInteger(), nullable=False),
        sa.Column("functionality", sa.Integer(), nullable=False),
        sa.Column("ui", sa.Integer(), nullable=False),
        sa.Column("code_quality", sa.Integer(), nullable=False),
        sa.Column("stability", sa.Integer(), nullable=False),
        sa.Column("originality", sa.Integer(), nullable=False),
        sa.Column("comment", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "functionality BETWEEN 0 AND 40 AND ui BETWEEN 0 AND 20 AND code_quality BETWEEN 0 AND 20 AND stability BETWEEN 0 AND 10 AND originality BETWEEN 0 AND 10",
            name="score_ranges",
        ),
        sa.ForeignKeyConstraint(
            ["submission_id"],
            ["submissions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("submission_id", "judge_telegram_id", name="uq_judge_score"),
    )
    op.create_index(op.f("ix_scores_submission_id"), "scores", ["submission_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_scores_submission_id"), table_name="scores")
    op.drop_table("scores")
    op.drop_table("submissions")
    op.drop_index(op.f("ix_payments_status"), table_name="payments")
    op.drop_table("payments")
    op.drop_index(op.f("ix_participations_user_id"), table_name="participations")
    op.drop_index(op.f("ix_participations_contest_id"), table_name="participations")
    op.drop_table("participations")
    op.drop_index(op.f("ix_login_sessions_user_id"), table_name="login_sessions")
    op.drop_index(op.f("ix_login_sessions_expires_at"), table_name="login_sessions")
    op.drop_table("login_sessions")
    op.drop_table("users")
    op.drop_index(op.f("ix_oauth_attempts_expires_at"), table_name="oauth_attempts")
    op.drop_table("oauth_attempts")
    op.drop_index(op.f("ix_notifications_status"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_available_at"), table_name="notifications")
    op.drop_table("notifications")
    op.drop_index(op.f("ix_contests_status"), table_name="contests")
    op.drop_index(op.f("ix_contests_starts_at"), table_name="contests")
    op.drop_index(op.f("ix_contests_ends_at"), table_name="contests")
    op.drop_table("contests")
    op.drop_table("audit_logs")
    # ### end Alembic commands ###
